theme: jekyll-theme-minimal
title: Nichole Breeland
logo: NicholeBreeland.github.io/headshot.jpeg
description: Social Cognition Researcher
twitter_url: www.twitter.com/NicholeBreeland
linkedin_url: https://www.linkedin.com/in/nichole-breeland-576002b2/
mail_url: n.breeland@auckland.ac.nz
