theme: jekyll-theme-minimal
title: Nichole Breeland
logo: NicholeBreeland.github.io/headshot.jpeg
description: Social Cognition Researcher
author: Nichole
  social:
    twitter: NicholeBreeland
    github:  NicholeBreeland
