theme: jekyll-theme-minimal
title: Nichole Breeland
logo: NicholeBreeland.github.io/rs.image0.jpeg
description: Social Cognition Researcher <br> <small>PhD in Psychology (Expected May 2021)<br> <i>The University of Auckland</i><br> BA in Psychology, Minor in Biology (2017) <br> <i>Pacific Lutheran University</i></small>
google_analytics: UA-179501623-1
