theme: jekyll-theme-minimal
title: Nichole Breeland
logo: NicholeBreeland.github.io/headshot.jpeg
description: Social Cognition Researcher
twitter_url:  http://www.twitter.com/NicholeBreeland/
linkedin_url: https://www.linkedin.com/in/nichole-breeland-576002b2/
mail_url: mailto:n.breeland@auckland.ac.nz
github_url:  http://www.github.com/NicholeBreeland/
